version: '3.7'

services:

  redis:
    image: redis:alpine
    container_name: sport_score-redis
    ports:
      - 6379

  postgres:
    image: postgres:16-alpine
    container_name: sport_score-postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport_score_development
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
