version: '3.7'

services:

  redis:
    image: redis:alpine
    container_name: ${APP_ID:-app}-redis
    ports:
      - ${REDIS_PORT:-6379}:6379

  postgres:
    image: postgres:16-alpine
    container_name: ${APP_ID:-app}-postgres
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
