version: '3.9'

services:

  app01: &app
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    hostname: app01
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-UTC}
    expose:
      - "8080"
    volumes:
      - .:/opt/app/api
    depends_on:
      - redis
      - postgres

  app02:
    <<: *app
    hostname: app02

  nginx:
    container_name: ${APP_ID:-app}-nginx
    image: nginx:1.25
    ports:
      - ${APP_PORT:-3000}:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01

  redis:
    image: redis:alpine
    container_name: ${APP_ID:-app}-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      TZ: ${TZ:-UTC}

  postgres:
    image: postgres:16-alpine
    container_name: ${APP_ID:-app}-postgres
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
