version: '3.9'

services:

  app01: &app
    build:
      dockerfile: Dockerfile
      context: .
    hostname: app01
    environment:
      APP_ID: ${APP_ID}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_TEST_USER: ${DB_TEST_USER:-postgres}
      DB_TEST_PASS: ${DB_TEST_PASS:-postgres}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_TEST_HOST: ${DB_TEST_HOST:-dbtest}
      DB_TEST_PORT: ${DB_TEST_PORT:-5432}
      TZ: ${TZ:-UTC}
    volumes:
      - .:/opt/app/api
    depends_on:
      - db
      - dbtest

  app02:
    <<: *app
    hostname: app02

  nginx:
    container_name: ${APP_ID:-app}-nginx
    image: nginx:1.25
    ports:
      - ${APP_PORT:-3000}:8080
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01

  redis:
    image: redis:alpine
    container_name: ${APP_ID:-app}-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      TZ: ${TZ:-UTC}

  db:
    image: postgres:16-alpine
    container_name: ${APP_ID:-app}-db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-UTC}
    volumes:
      - db:/var/lib/postgresql/data

  dbtest:
    image: postgres:16-alpine
    container_name: ${APP_ID:-app}-dbtest
    environment:
      POSTGRES_USER: ${DB_TEST_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_TEST_PASS:-postgres}
      POSTGRES_DB: ${DB_TEST_NAME}
      TZ: ${TZ:-UTC}

volumes:
  db:
